name: Painting
author: Warri, es3n1n
flag: maltactf{one_sweep_later...look_at_all_these_beautiful_flowers}
public: true
description: |-
  I love painting! I love it so much that, I left a flag in my masterpiece, which I saved inside THE microsoft paint binary!
