name: wintertime
author: Warri
public: true
flag: maltactf{s0_m4ny_l1n35_f0r_a-s1mpl3_CCAvuln...wh0se_p4p3r_came-out_alm0st_a_d3c4d3_ag0!}
description: |-
  Just another coding challenge... no Bob, do not POKE the angry italian
instancer: true