name: true random
author: quasar
public: true
flag: maltactf{f55dc5132f9529106d6e:3}
description: |-
  So it seems I need to transfer a flag or something. Fortunately - no cryptographer can break OTP! 
  Unfortunately... my cat may have shuffled my otp codes around. 
  Should be fine though, we have a few quantum circuits conveniently shared between us that we can use as our checksums! Surely the checksum of a random output won't let you break my OTP!
