name: matryoshka
author: Elvis
flag: maltactf{5Ecrets_WiThIn_Rus$14N_DOL1s}
public: true
description: |-
  Just like the nested Russian dolls after which this challenge is named, the deeper you dig, the more layers you’ll uncover   ![Image](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Poup%C3%A9es_russes.JPG/800px-Poup%C3%A9es_russes.JPG)

