apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: write-flag-where
spec:
  deployed: true
  powDifficultySeconds: 0
  horizontalPodAutoscalerSpec:
    maxReplicas: 4
    minReplicas: 2
    targetCPUUtilizationPercentage: 60
  podTemplate:
    template:
      spec:
        containers:
          - name: 'challenge'
            resources:
              requests:
                memory: "2000Mi"
                cpu: "2000m"
              limits:
                memory: "4000Mi"
                cpu: "4000m"
  network:
    public: true
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: true
    image: eu.gcr.io/friendly-maltese-citizens/write-flag-where-healthcheck:77bac2fc21af0adf9b48e28ddcb0bb80dba5df2522cc25413c031a412eacd1a8
  image: eu.gcr.io/friendly-maltese-citizens/write-flag-where-challenge:d6b865934f3d2f7df91181b410189d04a97797cfefa78ab300900111d7cabbde
