services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - FLAG=${FLAG:-maltactf{fakeflag}}
      - ANALYTICS_URL=${ANALYTICS_URL:-http://analytics:3000}
      - DOMAIN=${DOMAIN:-web:1337}
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined
    networks:
      - ctf-network
    depends_on:
      - analytics

  analytics:
    build: 
      context: ./analytics
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - ctf-network

networks:
  ctf-network:
    driver: bridge
